name: Build and deploy TurboRepo app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install pnpm globally (if not already installed)
        run: npm install -g pnpm

      - name: Install Turbo globally
        run: npm install -g turbo

      - name: npm install, build (TurboRepo)
        run: |
          pnpm install
          turbo run build my-app  # Build only the target application

      - name: Zip artifact for deployment (TurboRepo)
        run: |
          pnpm run build my-app --filter=deploy^...  # Build only the deployable parts
          cd apps/my-app/dist  # Assuming your output is in dist
          zip release.zip ./* -r        # Zip the contents of the output directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment (Optional)
        # Replace with your deployment script if needed
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'turbo'
          slot-name: 'production'
          package: .        # Deployment package location (adjust if using custom script)